package maestro

import (
	"github.com/PivotLLM/Maestro/global"
	"github.com/PivotLLM/toolspec"
)

func (p *Provider) getToolDefinitions() []toolspec.ToolDefinition {
	return []toolspec.ToolDefinition{
		{
			Name:        global.ToolStartHere,
			Description: "CALL THIS FIRST. Returns the Maestro orientation guide. Using Maestro without reading this risks errors and data loss.",
			Parameters:  []toolspec.Parameter{},
			Handler:     p.handleStartHere,
			Hints:       &toolspec.ToolHints{ReadOnly: toolspec.Allow(true)},
		},
		{
			Name:        global.ToolReferenceList,
			Description: "List all files in the built-in reference documentation. **Start by reading 'start.md' for orchestration guidance.** The reference section contains guidance on how to use Maestro effectively.",
			Parameters: []toolspec.Parameter{
				{Name: "prefix", Type: "string", Description: "Optional path prefix filter", Required: false},
			},
			Handler: p.handleReferenceList,
			Hints:   &toolspec.ToolHints{ReadOnly: toolspec.Allow(true)},
		},
		{
			Name:        global.ToolReferenceGet,
			Description: "Read a file from the built-in reference documentation. **New to Maestro? Read 'start.md' first for complete orchestration guidance.** Note: To copy a reference file to a project or playbook, use file_copy instead of get+put - it's more efficient and doesn't load content into the conversation.",
			Parameters: []toolspec.Parameter{
				{Name: "path", Type: "string", Description: "Path to the reference file. Start with 'start.md' for orchestration guidance, then explore phase-specific docs in 'phases/'", Required: false},
				{Name: "byte_offset", Type: "number", Description: "Byte position to start reading from, for chunked reading of large files (default: 0)", Required: false},
				{Name: "max_bytes", Type: "number", Description: "Maximum bytes to return in this chunk, for chunked reading of large files (default: 0 = entire file)", Required: false},
			},
			Handler: p.handleReferenceGet,
			Hints:   &toolspec.ToolHints{ReadOnly: toolspec.Allow(true)},
		},
		{
			Name:        global.ToolReferenceSearch,
			Description: "Search reference documentation by filename or content.",
			Parameters: []toolspec.Parameter{
				{Name: "query", Type: "string", Description: "Search query string", Required: false},
				{Name: "limit", Type: "number", Description: "Maximum number of results", Required: false},
				{Name: "offset", Type: "number", Description: "Number of results to skip", Required: false},
			},
			Handler: p.handleReferenceSearch,
			Hints:   &toolspec.ToolHints{ReadOnly: toolspec.Allow(true)},
		},
		{
			Name:        global.ToolPlaybookList,
			Description: "List all playbooks. Playbooks are user-created collections of reusable knowledge and procedures.",
			Parameters:  []toolspec.Parameter{},
			Handler:     p.handlePlaybookList,
			Hints:       &toolspec.ToolHints{ReadOnly: toolspec.Allow(true)},
		},
		{
			Name:        global.ToolPlaybookCreate,
			Description: "Create a new playbook.",
			Parameters: []toolspec.Parameter{
				{Name: "name", Type: "string", Description: "Playbook name (alphanumeric, hyphens, underscores)", Required: false},
			},
			Handler: p.handlePlaybookCreate,
			Hints:   nil,
		},
		{
			Name:        global.ToolPlaybookRename,
			Description: "Rename a playbook.",
			Parameters: []toolspec.Parameter{
				{Name: "name", Type: "string", Description: "Current playbook name", Required: false},
				{Name: "new_name", Type: "string", Description: "New playbook name", Required: false},
			},
			Handler: p.handlePlaybookRename,
			Hints:   nil,
		},
		{
			Name:        global.ToolPlaybookDelete,
			Description: "Delete a playbook and all its files.",
			Parameters: []toolspec.Parameter{
				{Name: "name", Type: "string", Description: "Playbook name", Required: false},
			},
			Handler: p.handlePlaybookDelete,
			Hints:   &toolspec.ToolHints{Destructive: toolspec.Allow(!p.markNonDestructive)},
		},
		{
			Name:        global.ToolPlaybookFileList,
			Description: "List files in a playbook.",
			Parameters: []toolspec.Parameter{
				{Name: "playbook", Type: "string", Description: "Playbook name", Required: false},
				{Name: "prefix", Type: "string", Description: "Optional path prefix filter", Required: false},
			},
			Handler: p.handlePlaybookFileList,
			Hints:   &toolspec.ToolHints{ReadOnly: toolspec.Allow(true)},
		},
		{
			Name:        global.ToolPlaybookFileGet,
			Description: "Read a file from a playbook. Note: To copy a file, use file_copy instead of get+put - it's more efficient and doesn't load content into the conversation.",
			Parameters: []toolspec.Parameter{
				{Name: "playbook", Type: "string", Description: "Playbook name", Required: false},
				{Name: "path", Type: "string", Description: "File path within the playbook", Required: false},
				{Name: "byte_offset", Type: "number", Description: "Byte position to start reading from, for chunked reading of large files (default: 0)", Required: false},
				{Name: "max_bytes", Type: "number", Description: "Maximum bytes to return in this chunk, for chunked reading of large files (default: 0 = entire file)", Required: false},
			},
			Handler: p.handlePlaybookFileGet,
			Hints:   &toolspec.ToolHints{ReadOnly: toolspec.Allow(true)},
		},
		{
			Name:        global.ToolPlaybookFilePut,
			Description: "Create or update a file in a playbook. Note: To copy a file, use file_copy instead of get+put - it's more efficient and doesn't load content into the conversation.",
			Parameters: []toolspec.Parameter{
				{Name: "playbook", Type: "string", Description: "Playbook name", Required: false},
				{Name: "path", Type: "string", Description: "File path within the playbook", Required: false},
				{Name: "content", Type: "string", Description: "File content (text only)", Required: false},
				{Name: "summary", Type: "string", Description: "Optional summary description", Required: false},
			},
			Handler: p.handlePlaybookFilePut,
			Hints:   nil,
		},
		{
			Name:        global.ToolPlaybookFileAppend,
			Description: "Append content to a file in a playbook. If the file exists, content is added to the end. If the file doesn't exist, it is created with the provided content.",
			Parameters: []toolspec.Parameter{
				{Name: "playbook", Type: "string", Description: "Playbook name", Required: false},
				{Name: "path", Type: "string", Description: "File path within the playbook", Required: false},
				{Name: "content", Type: "string", Description: "Content to append (text only)", Required: false},
				{Name: "summary", Type: "string", Description: "Optional summary description", Required: false},
			},
			Handler: p.handlePlaybookFileAppend,
			Hints:   nil,
		},
		{
			Name:        global.ToolPlaybookFileEdit,
			Description: "Edit a file in a playbook using search-and-replace. The old_string must exist in the file exactly as specified. If it appears multiple times, use replace_all=true.",
			Parameters: []toolspec.Parameter{
				{Name: "playbook", Type: "string", Description: "Playbook name", Required: false},
				{Name: "path", Type: "string", Description: "File path within the playbook", Required: false},
				{Name: "old_string", Type: "string", Description: "Exact text to find and replace (must exist in file)", Required: false},
				{Name: "new_string", Type: "string", Description: "Text to replace it with (can be empty string to delete)", Required: false},
				{Name: "replace_all", Type: "boolean", Description: "Replace all occurrences (default: false - fails if old_string appears multiple times)", Required: false},
			},
			Handler: p.handlePlaybookFileEdit,
			Hints:   nil,
		},
		{
			Name:        global.ToolPlaybookFileRename,
			Description: "Rename or move a file within a playbook.",
			Parameters: []toolspec.Parameter{
				{Name: "playbook", Type: "string", Description: "Playbook name", Required: false},
				{Name: "from_path", Type: "string", Description: "Current file path", Required: false},
				{Name: "to_path", Type: "string", Description: "New file path", Required: false},
			},
			Handler: p.handlePlaybookFileRename,
			Hints:   nil,
		},
		{
			Name:        global.ToolPlaybookFileDelete,
			Description: "Delete a file from a playbook.",
			Parameters: []toolspec.Parameter{
				{Name: "playbook", Type: "string", Description: "Playbook name", Required: false},
				{Name: "path", Type: "string", Description: "File path within the playbook", Required: false},
			},
			Handler: p.handlePlaybookFileDelete,
			Hints:   &toolspec.ToolHints{Destructive: toolspec.Allow(!p.markNonDestructive)},
		},
		{
			Name:        global.ToolPlaybookSearch,
			Description: "Search files in playbooks by filename or content.",
			Parameters: []toolspec.Parameter{
				{Name: "query", Type: "string", Description: "Search query string", Required: false},
				{Name: "playbook", Type: "string", Description: "Playbook name (optional, searches all if omitted)", Required: false},
				{Name: "limit", Type: "number", Description: "Maximum number of results", Required: false},
				{Name: "offset", Type: "number", Description: "Number of results to skip", Required: false},
			},
			Handler: p.handlePlaybookSearch,
			Hints:   &toolspec.ToolHints{ReadOnly: toolspec.Allow(true)},
		},
		{
			Name:        global.ToolProjectCreate,
			Description: "Create a new project with metadata.",
			Parameters: []toolspec.Parameter{
				{Name: "name", Type: "string", Description: "Project name (alphanumeric, hyphens, underscores)", Required: false},
				{Name: "title", Type: "string", Description: "Human-readable project title", Required: false},
				{Name: "description", Type: "string", Description: "Project description", Required: false},
				{Name: "context", Type: "string", Description: "Global context included in all task prompts (e.g., audit period, customer info)", Required: false},
				{Name: "status", Type: "string", Description: "Initial status (pending, in_progress, done, cancelled)", Required: false},
				{Name: "disclaimer_template", Type: "string", Description: "Path to disclaimer file for reports (e.g., 'playbook-name/templates/disclaimer.md') or 'none'. This text appears at the top of generated reports. Use it to disclose AI assistance.", Required: false},
			},
			Handler: p.handleProjectCreate,
			Hints:   nil,
		},
		{
			Name:        global.ToolProjectGet,
			Description: "Get project metadata including tasks.",
			Parameters: []toolspec.Parameter{
				{Name: "name", Type: "string", Description: "Project name", Required: false},
			},
			Handler: p.handleProjectGet,
			Hints:   &toolspec.ToolHints{ReadOnly: toolspec.Allow(true)},
		},
		{
			Name:        global.ToolProjectUpdate,
			Description: "Update project metadata.",
			Parameters: []toolspec.Parameter{
				{Name: "name", Type: "string", Description: "Project name", Required: false},
				{Name: "title", Type: "string", Description: "New title (optional)", Required: false},
				{Name: "description", Type: "string", Description: "New description (optional)", Required: false},
				{Name: "context", Type: "string", Description: "Global context included in all task prompts (optional)", Required: false},
				{Name: "status", Type: "string", Description: "New status (optional)", Required: false},
				{Name: "disclaimer_template", Type: "string", Description: "Path to disclaimer MD file for reports (optional)", Required: false},
			},
			Handler: p.handleProjectUpdate,
			Hints:   nil,
		},
		{
			Name:        global.ToolProjectList,
			Description: "List all projects.",
			Parameters: []toolspec.Parameter{
				{Name: "status", Type: "string", Description: "Filter by status (optional)", Required: false},
				{Name: "limit", Type: "number", Description: "Maximum number of projects to return", Required: false},
				{Name: "offset", Type: "number", Description: "Number of projects to skip", Required: false},
			},
			Handler: p.handleProjectList,
			Hints:   &toolspec.ToolHints{ReadOnly: toolspec.Allow(true)},
		},
		{
			Name:        global.ToolProjectDelete,
			Description: "Delete a project and all its contents.",
			Parameters: []toolspec.Parameter{
				{Name: "name", Type: "string", Description: "Project name", Required: false},
			},
			Handler: p.handleProjectDelete,
			Hints:   &toolspec.ToolHints{Destructive: toolspec.Allow(!p.markNonDestructive)},
		},
		{
			Name:        global.ToolProjectRename,
			Description: "Rename a project.",
			Parameters: []toolspec.Parameter{
				{Name: "name", Type: "string", Description: "Current project name", Required: false},
				{Name: "new_name", Type: "string", Description: "New project name", Required: false},
			},
			Handler: p.handleProjectRename,
			Hints:   nil,
		},
		{
			Name:        global.ToolProjectFileList,
			Description: "List files in a project's files directory.",
			Parameters: []toolspec.Parameter{
				{Name: "project", Type: "string", Description: "Project name", Required: false},
				{Name: "prefix", Type: "string", Description: "Optional path prefix filter", Required: false},
			},
			Handler: p.handleProjectFileList,
			Hints:   &toolspec.ToolHints{ReadOnly: toolspec.Allow(true)},
		},
		{
			Name:        global.ToolProjectFileGet,
			Description: "Read a file from a project. Note: To copy a file, use file_copy instead of get+put - it's more efficient and doesn't load content into the conversation.",
			Parameters: []toolspec.Parameter{
				{Name: "project", Type: "string", Description: "Project name", Required: false},
				{Name: "path", Type: "string", Description: "File path within the project", Required: false},
				{Name: "byte_offset", Type: "number", Description: "Byte position to start reading from, for chunked reading of large files (default: 0)", Required: false},
				{Name: "max_bytes", Type: "number", Description: "Maximum bytes to return in this chunk, for chunked reading of large files (default: 0 = entire file)", Required: false},
			},
			Handler: p.handleProjectFileGet,
			Hints:   &toolspec.ToolHints{ReadOnly: toolspec.Allow(true)},
		},
		{
			Name:        global.ToolProjectFilePut,
			Description: "Create or update a file in a project. Note: To copy a file, use file_copy instead of get+put - it's more efficient and doesn't load content into the conversation.",
			Parameters: []toolspec.Parameter{
				{Name: "project", Type: "string", Description: "Project name", Required: false},
				{Name: "path", Type: "string", Description: "File path within the project", Required: false},
				{Name: "content", Type: "string", Description: "File content (text only)", Required: false},
				{Name: "summary", Type: "string", Description: "Optional summary description", Required: false},
			},
			Handler: p.handleProjectFilePut,
			Hints:   nil,
		},
		{
			Name:        global.ToolProjectFileAppend,
			Description: "Append content to a file in a project. If the file exists, content is added to the end. If the file doesn't exist, it is created with the provided content.",
			Parameters: []toolspec.Parameter{
				{Name: "project", Type: "string", Description: "Project name", Required: false},
				{Name: "path", Type: "string", Description: "File path within the project", Required: false},
				{Name: "content", Type: "string", Description: "Content to append (text only)", Required: false},
				{Name: "summary", Type: "string", Description: "Optional summary description", Required: false},
			},
			Handler: p.handleProjectFileAppend,
			Hints:   nil,
		},
		{
			Name:        global.ToolProjectFileEdit,
			Description: "Edit a file in a project using search-and-replace. The old_string must exist in the file exactly as specified. If it appears multiple times, use replace_all=true.",
			Parameters: []toolspec.Parameter{
				{Name: "project", Type: "string", Description: "Project name", Required: false},
				{Name: "path", Type: "string", Description: "File path within the project", Required: false},
				{Name: "old_string", Type: "string", Description: "Exact text to find and replace (must exist in file)", Required: false},
				{Name: "new_string", Type: "string", Description: "Text to replace it with (can be empty string to delete)", Required: false},
				{Name: "replace_all", Type: "boolean", Description: "Replace all occurrences (default: false - fails if old_string appears multiple times)", Required: false},
			},
			Handler: p.handleProjectFileEdit,
			Hints:   nil,
		},
		{
			Name:        global.ToolProjectFileRename,
			Description: "Rename or move a file within a project.",
			Parameters: []toolspec.Parameter{
				{Name: "project", Type: "string", Description: "Project name", Required: false},
				{Name: "from_path", Type: "string", Description: "Current file path", Required: false},
				{Name: "to_path", Type: "string", Description: "New file path", Required: false},
			},
			Handler: p.handleProjectFileRename,
			Hints:   nil,
		},
		{
			Name:        global.ToolProjectFileDelete,
			Description: "Delete a file from a project.",
			Parameters: []toolspec.Parameter{
				{Name: "project", Type: "string", Description: "Project name", Required: false},
				{Name: "path", Type: "string", Description: "File path within the project", Required: false},
			},
			Handler: p.handleProjectFileDelete,
			Hints:   &toolspec.ToolHints{Destructive: toolspec.Allow(!p.markNonDestructive)},
		},
		{
			Name:        global.ToolProjectFileSearch,
			Description: "Search files in projects by filename or content.",
			Parameters: []toolspec.Parameter{
				{Name: "query", Type: "string", Description: "Search query string", Required: false},
				{Name: "project", Type: "string", Description: "Project name (optional, searches all if omitted)", Required: false},
				{Name: "limit", Type: "number", Description: "Maximum number of results", Required: false},
				{Name: "offset", Type: "number", Description: "Number of results to skip", Required: false},
			},
			Handler: p.handleProjectFileSearch,
			Hints:   &toolspec.ToolHints{ReadOnly: toolspec.Allow(true)},
		},
		{
			Name:        global.ToolProjectFileConvert,
			Description: "Convert files in a project to Markdown. Supports PDF, DOCX, and XLSX files.",
			Parameters: []toolspec.Parameter{
				{Name: "project", Type: "string", Description: "Project name", Required: false},
				{Name: "path", Type: "string", Description: "Path within project files directory. Must be a file if recursive=false, or a directory if recursive=true.", Required: false},
				{Name: "recursive", Type: "boolean", Description: "If true, recursively convert all files in directory. If false, convert single file. Default: false.", Required: false},
			},
			Handler: p.handleProjectFileConvert,
			Hints:   nil,
		},
		{
			Name:        global.ToolProjectFileExtract,
			Description: "Extract a zip archive within a project's files directory. Extracts to a directory with the same name as the archive (without .zip extension) in the same location.",
			Parameters: []toolspec.Parameter{
				{Name: "project", Type: "string", Description: "Project name", Required: false},
				{Name: "path", Type: "string", Description: "Path to the .zip file within the project files directory", Required: false},
				{Name: "overwrite", Type: "boolean", Description: "If true, overwrite existing files during extraction. Default: false (skip existing files).", Required: false},
				{Name: "convert", Type: "boolean", Description: "If true, convert extracted files (PDF, DOCX, XLSX) to Markdown after extraction. Default: false.", Required: false},
			},
			Handler: p.handleProjectFileExtract,
			Hints:   nil,
		},
		{
			Name:        global.ToolProjectLogAppend,
			Description: "Append a message to a project log.",
			Parameters: []toolspec.Parameter{
				{Name: "project", Type: "string", Description: "Project name", Required: false},
				{Name: "message", Type: "string", Description: "Log message", Required: false},
			},
			Handler: p.handleProjectLogAppend,
			Hints:   nil,
		},
		{
			Name:        global.ToolProjectLogGet,
			Description: "Get log entries from a project.",
			Parameters: []toolspec.Parameter{
				{Name: "project", Type: "string", Description: "Project name", Required: false},
				{Name: "limit", Type: "number", Description: "Maximum number of entries to return", Required: false},
				{Name: "offset", Type: "number", Description: "Number of entries to skip", Required: false},
			},
			Handler: p.handleProjectLogGet,
			Hints:   &toolspec.ToolHints{ReadOnly: toolspec.Allow(true)},
		},
		{
			Name:        global.ToolLLMList,
			Description: "List all configured LLMs with their IDs, names, and descriptions.",
			Parameters:  []toolspec.Parameter{},
			Handler:     p.handleLLMList,
			Hints:       &toolspec.ToolHints{ReadOnly: toolspec.Allow(true)},
		},
		{
			Name:        global.ToolLLMDispatch,
			Description: "Send a prompt to a configured LLM.",
			Parameters: []toolspec.Parameter{
				{Name: "llm_id", Type: "string", Description: "ID of the LLM to use (see llm_list)", Required: false},
				{Name: "prompt", Type: "string", Description: "The prompt to send to the LLM", Required: false},
			},
			Handler: p.handleLLMDispatch,
			Hints:   nil,
		},
		{
			Name:        global.ToolLLMTest,
			Description: "Test if an LLM is available and responding. Useful for pre-flight checks before starting long-running tasks.",
			Parameters: []toolspec.Parameter{
				{Name: "llm_id", Type: "string", Description: "ID of the LLM to test", Required: false},
			},
			Handler: p.handleLLMTest,
			Hints:   &toolspec.ToolHints{ReadOnly: toolspec.Allow(true)},
		},
		{
			Name:        global.ToolHealth,
			Description: "Check Maestro health status. Returns whether the system is healthy and any issues that need to be resolved, such as missing configuration or disabled LLMs.",
			Parameters:  []toolspec.Parameter{},
			Handler:     p.handleHealth,
			Hints:       &toolspec.ToolHints{ReadOnly: toolspec.Allow(true)},
		},
		{
			Name:        global.ToolFileCopy,
			Description: "Copy a file within or between domains (reference, playbooks, projects). More efficient than using get+put as it doesn't load file content into the conversation. Use this instead of get+put when copying files.",
			Parameters: []toolspec.Parameter{
				{Name: "from_path", Type: "string", Description: "Source file path", Required: false},
				{Name: "to_path", Type: "string", Description: "Destination file path", Required: false},
				{Name: "from_source", Type: "string", Description: "Source domain: 'project' (default), 'playbook', or 'reference'", Required: false},
				{Name: "from_project", Type: "string", Description: "Source project name (required when from_source is 'project')", Required: false},
				{Name: "from_playbook", Type: "string", Description: "Source playbook name (required when from_source is 'playbook')", Required: false},
				{Name: "to_source", Type: "string", Description: "Destination domain: 'project' (default) or 'playbook' (reference is read-only)", Required: false},
				{Name: "to_project", Type: "string", Description: "Destination project name (required when to_source is 'project')", Required: false},
				{Name: "to_playbook", Type: "string", Description: "Destination playbook name (required when to_source is 'playbook')", Required: false},
				{Name: "summary", Type: "string", Description: "Optional summary description for the destination file metadata", Required: false},
			},
			Handler: p.handleFileCopy,
			Hints:   nil,
		},
		{
			Name:        global.ToolFileDelete,
			Description: "Delete a file from a project or playbook domain. Reference is read-only and cannot be deleted from.",
			Parameters: []toolspec.Parameter{
				{Name: "path", Type: "string", Description: "File path to delete", Required: false},
				{Name: "source", Type: "string", Description: "Domain: 'project' (default) or 'playbook'", Required: false},
				{Name: "project", Type: "string", Description: "Project name (required when source is 'project')", Required: false},
				{Name: "playbook", Type: "string", Description: "Playbook name (required when source is 'playbook')", Required: false},
			},
			Handler: p.handleFileDelete,
			Hints:   &toolspec.ToolHints{Destructive: toolspec.Allow(!p.markNonDestructive)},
		},
		{
			Name:        global.ToolFileImport,
			Description: "Import external files into a project's files/imported/ directory. This bypasses the normal chroot restrictions to allow importing files from anywhere on the filesystem. Imported files can then be accessed via project_file_* tools.",
			Parameters: []toolspec.Parameter{
				{Name: "source", Type: "string", Description: "Source file or directory path (absolute path on the filesystem)", Required: false},
				{Name: "project", Type: "string", Description: "Target project name to import files into", Required: false},
				{Name: "recursive", Type: "boolean", Description: "If true, recursively import directories. Required when source is a directory.", Required: false},
				{Name: "convert", Type: "boolean", Description: "If true, automatically convert imported files (PDF, DOCX, XLSX) to Markdown after import.", Required: false},
			},
			Handler: p.handleFileImport,
			Hints:   nil,
		},
		{
			Name:        global.ToolReportList,
			Description: "List all reports in a project's reports directory.",
			Parameters: []toolspec.Parameter{
				{Name: "project", Type: "string", Description: "Project name", Required: false},
			},
			Handler: p.handleReportList,
			Hints:   &toolspec.ToolHints{ReadOnly: toolspec.Allow(true)},
		},
		{
			Name:        global.ToolReportRead,
			Description: "Read a report from a project. Reports are generated automatically by the runner.",
			Parameters: []toolspec.Parameter{
				{Name: "project", Type: "string", Description: "Project name", Required: false},
				{Name: "report", Type: "string", Description: "Report filename (e.g., '20251219-1234-Audit-Report.md')", Required: false},
				{Name: "byte_offset", Type: "number", Description: "Byte position to start reading from (default: 0)", Required: false},
				{Name: "max_bytes", Type: "number", Description: "Maximum bytes to return (default: 0 = entire file)", Required: false},
			},
			Handler: p.handleReportRead,
			Hints:   &toolspec.ToolHints{ReadOnly: toolspec.Allow(true)},
		},
		{
			Name:        global.ToolReportStart,
			Description: "Start a report session for a project. Sets a prefix (e.g., '20251219-1234-Audit-') that all subsequent report_append calls will use.",
			Parameters: []toolspec.Parameter{
				{Name: "project", Type: "string", Description: "Project name", Required: false},
				{Name: "title", Type: "string", Description: "Report title (used to generate prefix)", Required: false},
				{Name: "intro", Type: "string", Description: "Optional introductory paragraph to write to the main report", Required: false},
			},
			Handler: p.handleReportStart,
			Hints:   nil,
		},
		{
			Name:        global.ToolReportAppend,
			Description: "Append content to a report. Uses the active report prefix. If no session is active, auto-initializes with project name.",
			Parameters: []toolspec.Parameter{
				{Name: "project", Type: "string", Description: "Project name", Required: false},
				{Name: "content", Type: "string", Description: "Content to append (markdown)", Required: false},
				{Name: "report", Type: "string", Description: "Report name suffix (optional - omit for main report, e.g., 'Summary' creates <prefix>Summary.md)", Required: false},
			},
			Handler: p.handleReportAppend,
			Hints:   nil,
		},
		{
			Name:        global.ToolReportEnd,
			Description: "End the report session and clear the prefix. Future report_append calls will start a new session.",
			Parameters: []toolspec.Parameter{
				{Name: "project", Type: "string", Description: "Project name", Required: false},
			},
			Handler: p.handleReportEnd,
			Hints:   nil,
		},
		{
			Name:        global.ToolListList,
			Description: "List all lists in the specified source (project, playbook, or reference).",
			Parameters: []toolspec.Parameter{
				{Name: "source", Type: "string", Description: "Source domain: 'project' (default), 'playbook', or 'reference'", Required: false},
				{Name: "project", Type: "string", Description: "Project name (required when source is 'project')", Required: false},
				{Name: "playbook", Type: "string", Description: "Playbook name (required when source is 'playbook')", Required: false},
				{Name: "offset", Type: "number", Description: "Number of results to skip", Required: false},
				{Name: "limit", Type: "number", Description: "Maximum number of results", Required: false},
			},
			Handler: p.handleListList,
			Hints:   &toolspec.ToolHints{ReadOnly: toolspec.Allow(true)},
		},
		{
			Name:        global.ToolListGet,
			Description: "Get the full contents of a list including all items.",
			Parameters: []toolspec.Parameter{
				{Name: "list", Type: "string", Description: "List name", Required: false},
				{Name: "source", Type: "string", Description: "Source domain: 'project' (default), 'playbook', or 'reference'", Required: false},
				{Name: "project", Type: "string", Description: "Project name (required when source is 'project')", Required: false},
				{Name: "playbook", Type: "string", Description: "Playbook name (required when source is 'playbook')", Required: false},
			},
			Handler: p.handleListGet,
			Hints:   &toolspec.ToolHints{ReadOnly: toolspec.Allow(true)},
		},
		{
			Name:        global.ToolListGetSummary,
			Description: "Get list metadata with paginated items (content truncated to 100 chars).",
			Parameters: []toolspec.Parameter{
				{Name: "list", Type: "string", Description: "List name", Required: false},
				{Name: "source", Type: "string", Description: "Source domain: 'project' (default), 'playbook', or 'reference'", Required: false},
				{Name: "project", Type: "string", Description: "Project name (required when source is 'project')", Required: false},
				{Name: "playbook", Type: "string", Description: "Playbook name (required when source is 'playbook')", Required: false},
				{Name: "complete", Type: "string", Description: "Filter by complete status (projects only): 'true', 'false', or '' (no filter)", Required: false},
				{Name: "offset", Type: "number", Description: "Number of items to skip", Required: false},
				{Name: "limit", Type: "number", Description: "Maximum number of items", Required: false},
			},
			Handler: p.handleListGetSummary,
			Hints:   &toolspec.ToolHints{ReadOnly: toolspec.Allow(true)},
		},
		{
			Name:        global.ToolListCreate,
			Description: "Create a new list. Lists cannot be created in the reference domain.",
			Parameters: []toolspec.Parameter{
				{Name: "list", Type: "string", Description: "List name", Required: false},
				{Name: "name", Type: "string", Description: "Human-readable list name", Required: false},
				{Name: "source", Type: "string", Description: "Source domain: 'project' (default) or 'playbook'", Required: false},
				{Name: "project", Type: "string", Description: "Project name (required when source is 'project')", Required: false},
				{Name: "playbook", Type: "string", Description: "Playbook name (required when source is 'playbook')", Required: false},
				{Name: "description", Type: "string", Description: "List description (optional)", Required: false},
			},
			Handler: p.handleListCreate,
			Hints:   nil,
		},
		{
			Name:        global.ToolListDelete,
			Description: "Delete a list. Lists cannot be deleted from the reference domain.",
			Parameters: []toolspec.Parameter{
				{Name: "list", Type: "string", Description: "List name", Required: false},
				{Name: "source", Type: "string", Description: "Source domain: 'project' (default) or 'playbook'", Required: false},
				{Name: "project", Type: "string", Description: "Project name (required when source is 'project')", Required: false},
				{Name: "playbook", Type: "string", Description: "Playbook name (required when source is 'playbook')", Required: false},
			},
			Handler: p.handleListDelete,
			Hints:   &toolspec.ToolHints{Destructive: toolspec.Allow(!p.markNonDestructive)},
		},
		{
			Name:        global.ToolListRename,
			Description: "Rename a list. Lists cannot be renamed in the reference domain.",
			Parameters: []toolspec.Parameter{
				{Name: "list", Type: "string", Description: "Current list name", Required: false},
				{Name: "new_list", Type: "string", Description: "New list name", Required: false},
				{Name: "source", Type: "string", Description: "Source domain: 'project' (default) or 'playbook'", Required: false},
				{Name: "project", Type: "string", Description: "Project name (required when source is 'project')", Required: false},
				{Name: "playbook", Type: "string", Description: "Playbook name (required when source is 'playbook')", Required: false},
			},
			Handler: p.handleListRename,
			Hints:   nil,
		},
		{
			Name:        global.ToolListCopy,
			Description: "Copy a list from one location to another. Supports copying between projects, playbooks, and reference (source only).",
			Parameters: []toolspec.Parameter{
				{Name: "from_list", Type: "string", Description: "Source list name", Required: false},
				{Name: "to_list", Type: "string", Description: "Destination list name", Required: false},
				{Name: "from_source", Type: "string", Description: "Source domain: 'project' (default), 'playbook', or 'reference'", Required: false},
				{Name: "from_project", Type: "string", Description: "Source project name (when from_source is 'project')", Required: false},
				{Name: "from_playbook", Type: "string", Description: "Source playbook name (when from_source is 'playbook')", Required: false},
				{Name: "to_source", Type: "string", Description: "Destination domain: 'project' (default) or 'playbook'", Required: false},
				{Name: "to_project", Type: "string", Description: "Destination project name (when to_source is 'project')", Required: false},
				{Name: "to_playbook", Type: "string", Description: "Destination playbook name (when to_source is 'playbook')", Required: false},
				{Name: "sample", Type: "number", Description: "Randomly sample N items from the source list instead of copying all. Useful for test audits.", Required: false},
			},
			Handler: p.handleListCopy,
			Hints:   nil,
		},
		{
			Name:        global.ToolListItemAdd,
			Description: "Add a new item to a list. Item IDs are auto-generated.",
			Parameters: []toolspec.Parameter{
				{Name: "list", Type: "string", Description: "List name", Required: false},
				{Name: "title", Type: "string", Description: "Short item title (displayed in summaries)", Required: false},
				{Name: "content", Type: "string", Description: "Full item content (used for task execution)", Required: false},
				{Name: "source", Type: "string", Description: "Source domain: 'project' (default) or 'playbook'", Required: false},
				{Name: "project", Type: "string", Description: "Project name (required when source is 'project')", Required: false},
				{Name: "playbook", Type: "string", Description: "Playbook name (required when source is 'playbook')", Required: false},
				{Name: "source_doc", Type: "string", Description: "Source document reference (optional)", Required: false},
				{Name: "section", Type: "string", Description: "Section within source document (optional)", Required: false},
			},
			Handler: p.handleListItemAdd,
			Hints:   nil,
		},
		{
			Name:        global.ToolListItemUpdate,
			Description: "Update an existing item in a list. Only specified fields are updated.",
			Parameters: []toolspec.Parameter{
				{Name: "list", Type: "string", Description: "List name", Required: false},
				{Name: "id", Type: "string", Description: "Item identifier", Required: false},
				{Name: "source", Type: "string", Description: "Source domain: 'project' (default) or 'playbook'", Required: false},
				{Name: "project", Type: "string", Description: "Project name (required when source is 'project')", Required: false},
				{Name: "playbook", Type: "string", Description: "Playbook name (required when source is 'playbook')", Required: false},
				{Name: "title", Type: "string", Description: "New item title (optional)", Required: false},
				{Name: "content", Type: "string", Description: "New item content (optional)", Required: false},
				{Name: "source_doc", Type: "string", Description: "New source document reference (optional)", Required: false},
				{Name: "section", Type: "string", Description: "New section (optional)", Required: false},
				{Name: "clear_tags", Type: "boolean", Description: "Set to true to clear all tags", Required: false},
				{Name: "complete", Type: "boolean", Description: "Mark item as complete (true) or incomplete (false). Cannot be set to true for playbook lists.", Required: false},
			},
			Handler: p.handleListItemUpdate,
			Hints:   nil,
		},
		{
			Name:        global.ToolListItemRemove,
			Description: "Remove an item from a list.",
			Parameters: []toolspec.Parameter{
				{Name: "list", Type: "string", Description: "List name", Required: false},
				{Name: "id", Type: "string", Description: "Item identifier", Required: false},
				{Name: "source", Type: "string", Description: "Source domain: 'project' (default) or 'playbook'", Required: false},
				{Name: "project", Type: "string", Description: "Project name (required when source is 'project')", Required: false},
				{Name: "playbook", Type: "string", Description: "Playbook name (required when source is 'playbook')", Required: false},
			},
			Handler: p.handleListItemRemove,
			Hints:   &toolspec.ToolHints{Destructive: toolspec.Allow(!p.markNonDestructive)},
		},
		{
			Name:        global.ToolListItemRename,
			Description: "Rename an item's ID. The new ID must be unique within the list.",
			Parameters: []toolspec.Parameter{
				{Name: "list", Type: "string", Description: "List name", Required: false},
				{Name: "id", Type: "string", Description: "Current item identifier", Required: false},
				{Name: "new_id", Type: "string", Description: "New item identifier", Required: false},
				{Name: "source", Type: "string", Description: "Source domain: 'project' (default) or 'playbook'", Required: false},
				{Name: "project", Type: "string", Description: "Project name (required when source is 'project')", Required: false},
				{Name: "playbook", Type: "string", Description: "Playbook name (required when source is 'playbook')", Required: false},
			},
			Handler: p.handleListItemRename,
			Hints:   nil,
		},
		{
			Name:        global.ToolListItemGet,
			Description: "Get a single item from a list by ID.",
			Parameters: []toolspec.Parameter{
				{Name: "list", Type: "string", Description: "List name", Required: false},
				{Name: "id", Type: "string", Description: "Item identifier", Required: false},
				{Name: "source", Type: "string", Description: "Source domain: 'project' (default), 'playbook', or 'reference'", Required: false},
				{Name: "project", Type: "string", Description: "Project name (required when source is 'project')", Required: false},
				{Name: "playbook", Type: "string", Description: "Playbook name (required when source is 'playbook')", Required: false},
			},
			Handler: p.handleListItemGet,
			Hints:   &toolspec.ToolHints{ReadOnly: toolspec.Allow(true)},
		},
		{
			Name:        global.ToolListItemSearch,
			Description: "Search for items in a list. Query matches id or content (case-insensitive). All filters are ANDed.",
			Parameters: []toolspec.Parameter{
				{Name: "list", Type: "string", Description: "List name", Required: false},
				{Name: "source", Type: "string", Description: "Source domain: 'project' (default), 'playbook', or 'reference'", Required: false},
				{Name: "project", Type: "string", Description: "Project name (required when source is 'project')", Required: false},
				{Name: "playbook", Type: "string", Description: "Playbook name (required when source is 'playbook')", Required: false},
				{Name: "query", Type: "string", Description: "Search query (matches id or content, case-insensitive)", Required: false},
				{Name: "source_doc", Type: "string", Description: "Filter by source document (exact match)", Required: false},
				{Name: "section", Type: "string", Description: "Filter by section (exact match)", Required: false},
				{Name: "complete", Type: "string", Description: "Filter by complete status (projects only): 'true', 'false', or '' (no filter)", Required: false},
				{Name: "offset", Type: "number", Description: "Number of results to skip", Required: false},
				{Name: "limit", Type: "number", Description: "Maximum number of results", Required: false},
			},
			Handler: p.handleListItemSearch,
			Hints:   &toolspec.ToolHints{ReadOnly: toolspec.Allow(true)},
		},
		{
			Name:        global.ToolListCreateTasks,
			Description: "Create tasks from list items. Creates one task per item with item context appended to the prompt.",
			Parameters: []toolspec.Parameter{
				{Name: "list", Type: "string", Description: "List name", Required: false},
				{Name: "project", Type: "string", Description: "Target project for created tasks", Required: false},
				{Name: "type", Type: "string", Description: "Task type for all created tasks", Required: false},
				{Name: "list_source", Type: "string", Description: "Source domain for the list: 'project' (default), 'playbook', or 'reference'", Required: false},
				{Name: "list_project", Type: "string", Description: "Project containing the list (when list_source is 'project')", Required: false},
				{Name: "list_playbook", Type: "string", Description: "Playbook containing the list (when list_source is 'playbook')", Required: false},
				{Name: "path", Type: "string", Description: "Task set path for created tasks (e.g., 'analysis', 'analysis/code')", Required: false},
				{Name: "title_template", Type: "string", Description: "Task title template. Use {{title}} for item title, {{id}} for item ID. Default: '{{title}}'", Required: false},
				{Name: "priority", Type: "number", Description: "Task priority for all created tasks", Required: false},
				{Name: "llm_model_id", Type: "string", Description: "LLM model ID for runner execution", Required: false},
				{Name: "instructions_file", Type: "string", Description: "Path to instructions file. For 'playbook' source, path MUST start with playbook name: 'playbook-name/path/file.md'. For 'project' source (uses target project) or 'reference' source, use relative path: 'path/file.md'.", Required: false},
				{Name: "instructions_file_source", Type: "string", Description: "Source type for instructions_file: 'project' (default - uses project's files directory), 'playbook' (uses playbook files), or 'reference' (uses embedded reference docs).", Required: false},
				{Name: "instructions_text", Type: "string", Description: "Inline instructions text", Required: false},
				{Name: "prompt", Type: "string", Description: "Base prompt (item context will be appended)", Required: false},
				{Name: "qa_enabled", Type: "boolean", Description: "Enable QA phase for this task", Required: false},
				{Name: "qa_instructions_file", Type: "string", Description: "QA instructions file path", Required: false},
				{Name: "qa_instructions_file_source", Type: "string", Description: "Source for QA instructions_file", Required: false},
				{Name: "qa_instructions_text", Type: "string", Description: "QA inline instructions text", Required: false},
				{Name: "qa_prompt", Type: "string", Description: "QA direct prompt text", Required: false},
				{Name: "qa_llm_model_id", Type: "string", Description: "QA LLM model ID", Required: false},
				{Name: "sample", Type: "number", Description: "Randomly sample N items from the list instead of using all items. Useful for test audits.", Required: false},
				{Name: "parallel", Type: "boolean", Description: "Enable parallel task execution. Set to true if tasks are independent and can run concurrently for efficiency. Default: false (sequential).", Required: false},
			},
			Handler: p.handleListCreateTasks,
			Hints:   nil,
		},
		{
			Name:        global.ToolTaskSetCreate,
			Description: "Create a new task set at a given path within a project.",
			Parameters: []toolspec.Parameter{
				{Name: "project", Type: "string", Description: "Project name", Required: false},
				{Name: "path", Type: "string", Description: "Task set path (e.g., 'analysis', 'analysis/code', max 3 levels)", Required: false},
				{Name: "title", Type: "string", Description: "Task set title", Required: false},
				{Name: "description", Type: "string", Description: "Task set description", Required: false},
				{Name: "parallel", Type: "boolean", Description: "Enable parallel task execution. Set to true if tasks are independent and can run concurrently for efficiency. Default: false (sequential).", Required: false},
				{Name: "worker_response_template", Type: "string", Description: "Path to JSON schema file for worker responses", Required: false},
				{Name: "worker_report_template", Type: "string", Description: "Path to markdown template for worker reports", Required: false},
				{Name: "qa_response_template", Type: "string", Description: "Path to JSON schema file for QA responses", Required: false},
				{Name: "qa_report_template", Type: "string", Description: "Path to markdown template for QA reports", Required: false},
				{Name: "skip_validation", Type: "boolean", Description: "Skip schema validation and report generation for this task set (default: false)", Required: false},
				{Name: "callback_url", Type: "string", Description: "URL to POST completion notification when tasks finish", Required: false},
			},
			Handler: p.handleTaskSetCreate,
			Hints:   nil,
		},
		{
			Name:        global.ToolTaskSetGet,
			Description: "Get a task set by path, including all its tasks.",
			Parameters: []toolspec.Parameter{
				{Name: "project", Type: "string", Description: "Project name", Required: false},
				{Name: "path", Type: "string", Description: "Task set path", Required: false},
			},
			Handler: p.handleTaskSetGet,
			Hints:   &toolspec.ToolHints{ReadOnly: toolspec.Allow(true)},
		},
		{
			Name:        global.ToolTaskSetList,
			Description: "List task sets in a project, optionally filtered by path prefix.",
			Parameters: []toolspec.Parameter{
				{Name: "project", Type: "string", Description: "Project name", Required: false},
				{Name: "path", Type: "string", Description: "Path prefix to filter by (optional)", Required: false},
			},
			Handler: p.handleTaskSetList,
			Hints:   &toolspec.ToolHints{ReadOnly: toolspec.Allow(true)},
		},
		{
			Name:        global.ToolTaskSetUpdate,
			Description: "Update a task set's metadata.",
			Parameters: []toolspec.Parameter{
				{Name: "project", Type: "string", Description: "Project name", Required: false},
				{Name: "path", Type: "string", Description: "Task set path", Required: false},
				{Name: "title", Type: "string", Description: "New title (optional)", Required: false},
				{Name: "description", Type: "string", Description: "New description (optional)", Required: false},
				{Name: "parallel", Type: "string", Description: "Set parallel execution: 'true' or 'false'. Use true if tasks are independent (optional).", Required: false},
				{Name: "worker_response_template", Type: "string", Description: "Path to JSON schema file for worker responses", Required: false},
				{Name: "worker_report_template", Type: "string", Description: "Path to markdown template for worker reports", Required: false},
				{Name: "qa_response_template", Type: "string", Description: "Path to JSON schema file for QA responses", Required: false},
				{Name: "qa_report_template", Type: "string", Description: "Path to markdown template for QA reports", Required: false},
				{Name: "skip_validation", Type: "string", Description: "Set skip_validation: 'true' or 'false' (optional)", Required: false},
				{Name: "callback_url", Type: "string", Description: "URL to POST completion notification when tasks finish (optional)", Required: false},
			},
			Handler: p.handleTaskSetUpdate,
			Hints:   nil,
		},
		{
			Name:        global.ToolTaskDispatch,
			Description: "Create and immediately execute a single task asynchronously. Returns immediately with task UUID and status 'running'. Optionally fires a callback when complete.",
			Parameters: []toolspec.Parameter{
				{Name: "project", Type: "string", Description: "Project name", Required: false},
				{Name: "path", Type: "string", Description: "Taskset path (auto-generated as 'dispatch/<uuid8>' if omitted)", Required: false},
				{Name: "title", Type: "string", Description: "Task title (default: 'Dispatched task')", Required: false},
				{Name: "llm_model_id", Type: "string", Description: "LLM model ID to use", Required: false},
				{Name: "prompt", Type: "string", Description: "Inline prompt text", Required: false},
				{Name: "instructions_text", Type: "string", Description: "Multi-line instructions text", Required: false},
				{Name: "instructions_file", Type: "string", Description: "Instructions file path", Required: false},
				{Name: "instructions_file_source", Type: "string", Description: "Source for instructions file: project, playbook, or reference", Required: false},
				{Name: "callback_url", Type: "string", Description: "URL to POST completion notification", Required: false},
			},
			Handler: p.handleTaskDispatch,
			Hints:   nil,
		},
		{
			Name:        global.ToolTaskSetDelete,
			Description: "Delete a task set and all its tasks.",
			Parameters: []toolspec.Parameter{
				{Name: "project", Type: "string", Description: "Project name", Required: false},
				{Name: "path", Type: "string", Description: "Task set path", Required: false},
			},
			Handler: p.handleTaskSetDelete,
			Hints:   &toolspec.ToolHints{Destructive: toolspec.Allow(!p.markNonDestructive)},
		},
		{
			Name:        global.ToolTaskSetReset,
			Description: "Reset tasks in a task set to waiting status. Requires 'mode' parameter to specify which tasks to reset.",
			Parameters: []toolspec.Parameter{
				{Name: "project", Type: "string", Description: "Project name", Required: false},
				{Name: "path", Type: "string", Description: "Task set path", Required: false},
				{Name: "mode", Type: "string", Description: "Reset mode: 'all' to reset all tasks, 'failed' to reset only failed tasks", Required: false},
				{Name: "delete_results", Type: "boolean", Description: "Delete results files from disk (default: true)", Required: false},
				{Name: "end_report", Type: "boolean", Description: "End the current report session (default: false). When true, response includes reminder to call report_start before running tasks.", Required: false},
			},
			Handler: p.handleTaskSetReset,
			Hints:   nil,
		},
		{
			Name:        global.ToolTaskCreate,
			Description: "Create a new task within a task set. At least one prompt field is required.",
			Parameters: []toolspec.Parameter{
				{Name: "project", Type: "string", Description: "Project name", Required: false},
				{Name: "path", Type: "string", Description: "Task set path", Required: false},
				{Name: "title", Type: "string", Description: "Task title", Required: false},
				{Name: "type", Type: "string", Description: "Task type for filtering/grouping", Required: false},
				{Name: "instructions_file", Type: "string", Description: "Path to instructions file", Required: false},
				{Name: "instructions_file_source", Type: "string", Description: "Source for instructions_file: 'project', 'playbook', or 'reference'", Required: false},
				{Name: "instructions_text", Type: "string", Description: "Inline instructions text", Required: false},
				{Name: "prompt", Type: "string", Description: "Direct prompt text", Required: false},
				{Name: "llm_model_id", Type: "string", Description: "LLM model ID for execution", Required: false},
				{Name: "qa_enabled", Type: "boolean", Description: "Enable QA phase for this task", Required: false},
				{Name: "qa_instructions_file", Type: "string", Description: "QA instructions file path", Required: false},
				{Name: "qa_instructions_file_source", Type: "string", Description: "Source for QA instructions_file", Required: false},
				{Name: "qa_instructions_text", Type: "string", Description: "QA inline instructions text", Required: false},
				{Name: "qa_prompt", Type: "string", Description: "QA direct prompt text", Required: false},
				{Name: "qa_llm_model_id", Type: "string", Description: "QA LLM model ID", Required: false},
				{Name: "qa_max_iterations", Type: "number", Description: "Maximum QA retry iterations", Required: false},
			},
			Handler: p.handleTaskCreate,
			Hints:   nil,
		},
		{
			Name:        global.ToolTaskGet,
			Description: "Get a task by UUID or by path and ID.",
			Parameters: []toolspec.Parameter{
				{Name: "project", Type: "string", Description: "Project name", Required: false},
				{Name: "uuid", Type: "string", Description: "Task UUID (preferred)", Required: false},
				{Name: "path", Type: "string", Description: "Task set path (required with id)", Required: false},
				{Name: "id", Type: "number", Description: "Task ID within task set (required with path)", Required: false},
			},
			Handler: p.handleTaskGet,
			Hints:   &toolspec.ToolHints{ReadOnly: toolspec.Allow(true)},
		},
		{
			Name:        global.ToolTaskList,
			Description: "List tasks, optionally filtered by path, status, or type.",
			Parameters: []toolspec.Parameter{
				{Name: "project", Type: "string", Description: "Project name", Required: false},
				{Name: "path", Type: "string", Description: "Task set path to list tasks from (optional, lists all if empty)", Required: false},
				{Name: "status", Type: "string", Description: "Filter by work status: waiting, processing, done, failed", Required: false},
				{Name: "type", Type: "string", Description: "Filter by task type", Required: false},
				{Name: "offset", Type: "number", Description: "Number of tasks to skip", Required: false},
				{Name: "limit", Type: "number", Description: "Maximum number of tasks to return", Required: false},
			},
			Handler: p.handleTaskList,
			Hints:   &toolspec.ToolHints{ReadOnly: toolspec.Allow(true)},
		},
		{
			Name:        global.ToolTaskUpdate,
			Description: "Update a task's metadata, instructions, or prompts.",
			Parameters: []toolspec.Parameter{
				{Name: "project", Type: "string", Description: "Project name", Required: false},
				{Name: "uuid", Type: "string", Description: "Task UUID", Required: false},
				{Name: "title", Type: "string", Description: "New title (optional)", Required: false},
				{Name: "type", Type: "string", Description: "New type (optional)", Required: false},
				{Name: "work_status", Type: "string", Description: "New work status (optional)", Required: false},
				{Name: "instructions_file", Type: "string", Description: "Path to instructions file (validated before update)", Required: false},
				{Name: "instructions_file_source", Type: "string", Description: "Source for instructions_file: 'project', 'playbook', or 'reference'", Required: false},
				{Name: "instructions_text", Type: "string", Description: "Inline instructions text", Required: false},
				{Name: "prompt", Type: "string", Description: "Direct prompt text", Required: false},
				{Name: "llm_model_id", Type: "string", Description: "LLM model ID for task execution", Required: false},
				{Name: "qa_instructions_file", Type: "string", Description: "Path to QA instructions file (validated before update)", Required: false},
				{Name: "qa_instructions_file_source", Type: "string", Description: "Source for QA instructions_file: 'project', 'playbook', or 'reference'", Required: false},
				{Name: "qa_instructions_text", Type: "string", Description: "QA inline instructions text", Required: false},
				{Name: "qa_prompt", Type: "string", Description: "QA direct prompt text", Required: false},
				{Name: "qa_llm_model_id", Type: "string", Description: "QA LLM model ID", Required: false},
			},
			Handler: p.handleTaskUpdate,
			Hints:   nil,
		},
		{
			Name:        global.ToolTaskDelete,
			Description: "Delete a task by UUID.",
			Parameters: []toolspec.Parameter{
				{Name: "project", Type: "string", Description: "Project name", Required: false},
				{Name: "uuid", Type: "string", Description: "Task UUID", Required: false},
			},
			Handler: p.handleTaskDelete,
			Hints:   &toolspec.ToolHints{Destructive: toolspec.Allow(!p.markNonDestructive)},
		},
		{
			Name:        global.ToolTaskRun,
			Description: "Run eligible tasks for a project. Tasks in 'waiting' or 'retry' status are executed. Returns immediately with count of tasks queued.",
			Parameters: []toolspec.Parameter{
				{Name: "project", Type: "string", Description: "Project name", Required: false},
				{Name: "path", Type: "string", Description: "Task set path prefix to filter (optional)", Required: false},
				{Name: "type", Type: "string", Description: "Filter by task type (optional)", Required: false},
				{Name: "parallel", Type: "string", Description: "Override taskset parallel setting: 'true' or 'false' (optional, defaults to taskset setting)", Required: false},
			},
			Handler: p.handleTaskRun,
			Hints:   nil,
		},
		{
			Name:        global.ToolTaskStatus,
			Description: "Get current status of tasks in a project, including counts by status and whether a run is in progress.",
			Parameters: []toolspec.Parameter{
				{Name: "project", Type: "string", Description: "Project name", Required: false},
				{Name: "path", Type: "string", Description: "Task set path prefix to filter (optional)", Required: false},
				{Name: "type", Type: "string", Description: "Filter by task type (optional)", Required: false},
			},
			Handler: p.handleTaskStatus,
			Hints:   &toolspec.ToolHints{ReadOnly: toolspec.Allow(true)},
		},
		{
			Name:        global.ToolTaskResults,
			Description: "Get task execution results. Returns completed task results with their outputs.",
			Parameters: []toolspec.Parameter{
				{Name: "project", Type: "string", Description: "Project name", Required: false},
				{Name: "path", Type: "string", Description: "Task set path prefix to filter (optional)", Required: false},
				{Name: "task_id", Type: "number", Description: "Specific task ID to get result for (optional)", Required: false},
				{Name: "status", Type: "string", Description: "Filter by status: done, failed (optional)", Required: false},
				{Name: "offset", Type: "number", Description: "Number of results to skip (default: 0)", Required: false},
				{Name: "limit", Type: "number", Description: "Maximum number of results (default: 50)", Required: false},
				{Name: "summary", Type: "boolean", Description: "If true, returns only task_id, task_uuid, task_title, work_status (default: false)", Required: false},
				{Name: "worker_pattern", Type: "string", Description: "Regex pattern to match against worker response (optional)", Required: false},
				{Name: "qa_pattern", Type: "string", Description: "Regex pattern to match against QA response (optional). If both patterns provided, uses OR logic.", Required: false},
			},
			Handler: p.handleTaskResults,
			Hints:   &toolspec.ToolHints{ReadOnly: toolspec.Allow(true)},
		},
		{
			Name:        global.ToolTaskResultGet,
			Description: "Get a single task result by UUID. Returns worker/QA responses without history or prompts. Includes worker_response_template for supervisor updates.",
			Parameters: []toolspec.Parameter{
				{Name: "project", Type: "string", Description: "Project name", Required: false},
				{Name: "uuid", Type: "string", Description: "Task UUID", Required: false},
			},
			Handler: p.handleTaskResultGet,
			Hints:   &toolspec.ToolHints{ReadOnly: toolspec.Allow(true)},
		},
		{
			Name:        global.ToolTaskReport,
			Description: "Generate a report from task results. Supports filtering and multiple output formats.",
			Parameters: []toolspec.Parameter{
				{Name: "project", Type: "string", Description: "Project name", Required: false},
				{Name: "path", Type: "string", Description: "Task set path prefix to filter (optional)", Required: false},
				{Name: "status", Type: "string", Description: "Filter by work status (optional)", Required: false},
				{Name: "type", Type: "string", Description: "Filter by task type (optional)", Required: false},
				{Name: "qa_passed", Type: "boolean", Description: "Filter by QA passed status (optional)", Required: false},
				{Name: "qa_severity", Type: "string", Description: "Filter by QA severity (optional)", Required: false},
				{Name: "format", Type: "string", Description: "Output format: markdown (default) or json", Required: false},
				{Name: "output", Type: "string", Description: "File path to save report (optional)", Required: false},
			},
			Handler: p.handleTaskReport,
			Hints:   &toolspec.ToolHints{ReadOnly: toolspec.Allow(true)},
		},
		{
			Name:        global.ToolSupervisorUpdate,
			Description: "Allows a supervisor to replace the worker response with their own content. The response must pass template validation. History is append-only.",
			Parameters:  []toolspec.Parameter{
				{Name: "project", Type: "string", Description: "Project name", Required: true},
				{Name: "uuid", Type: "string", Description: "Task UUID", Required: true},
				{Name: "response", Type: "string", Description: "Supervisor's replacement response (must match worker_response_template if defined)", Required: true},
			},
			Handler: p.handleSupervisorUpdate,
			Hints:   nil,
		},
		{
			Name:        global.ToolReportCreate,
			Description: "Generate reports from task results. Uses the same report generation logic as the runner. Supports optional path filtering.",
			Parameters:  []toolspec.Parameter{
				{Name: "project", Type: "string", Description: "Project name", Required: true},
				{Name: "path", Type: "string", Description: "Task set path prefix to filter (optional)", Required: false},
			},
			Handler: p.handleReportCreate,
			Hints:   nil,
		},
	}
}
